version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      # Check for npm updates on Sundays
      time: "15:20"
      timezone: "Asia/Kolkata"
    # Labels on pull requests for security and version updates
    labels:
      - "npm dependencies"